### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by troeger** [troeger/kubeportal#2]
- [x] Installation
- [x] Configuration of AD auth
- [x] Screenshots of frontend and backend user management
- [x] K8S synchronization, management of namespaces and service accounts
- [x] Grafana example configuration

**Comment by leonardlorenz** [comment]
Please add documentation for OAuth2 configuration.

**Comment by troeger** [comment]
See latest commits, now available at https://kubeportal.readthedocs.io/en/latest/
