### ISSUE TITLE
Allow filtering of namespace list

### ISSUE THREAD

**Issue by troeger** [troeger/kubeportal#24]
It should be possible to sort out only namespaces that are currently visible. See also #18

**Comment by leonardlorenz** [comment]
Namespace filtering is now implemented to the point where critical code has to be touched. Assigning the issue back to you.

**Comment by troeger** [comment]
Depends on #34, since changes are touching the sync code.

**Comment by leonardlorenz** [comment]
KubePortal crashes on namespace creation because of a bad query in KubernetesNamespaceManager.get_queryset() in models.py.

```
django.core.exceptions.FieldError: Related Field got invalid lookup: is_null
```

Investigating. Please don't merge yet
