### ISSUE TITLE
More descriptive error messages when k8s is not reachable.

### ISSUE THREAD

**Issue by leonardlorenz** [troeger/kubeportal#26]
We're trying to avoid Error 500 messages.

**Comment by troeger** [comment]
We need to wrap all Kubernetes data fetching activities into according try-except blocks. Every catch block should trigger a Django popup, and should mitigate to some empty result being shown for the user

**Comment by troeger** [comment]
With the recent test coverage > 80% - not triggering 500 errors - I declare this problem to be solved.
