### ISSUE TITLE
Proper logging, log levels

### ISSUE THREAD

**Issue by leonardlorenz** [troeger/kubeportal#37]
Implement proper logging and create new environment variable (for example) to set log levels.

**Comment by troeger** [comment]
Given the fact that Docker is our only supported deployment method, it would would be feasible if production logging always ends up as screen output. This makes it accessible in Kuberneters in the natural way.

**Comment by troeger** [comment]
I would especially like to see request logging and Python social logging. This would make it easier to find OAuth config problems.

**Comment by leonardlorenz** [comment]
Needs testing. Logging k8s operations seems to work already.

**Comment by troeger** [comment]
Fixed with v0.2.1
